### ISSUE TITLE
motif for indels (ID18)

### ISSUE THREAD

**Issue by ykginoue** [ProjectsVanBox/colibactin_detection#1]
I am interested in the colibactin motif to see whether a mutation is likely be related to colibactin. In the original article, there was a clear notice of what an single base substitution colibactin-motif will be(SBS88 signature). However, I could not find an explanation of the indel colibactin-motif(ID18 signature). It seemed that the motif is AA in the -3-4bp before the deletion, but how about the bases in -2,-1 or +1? Will it be A on -2 and -1 as in the paper from "Mutational signature in colorectal cancer caused by genotoxic pks E.coliI"? I tried to find the indel-motif that has been used by looking into this R script, but unfortunately could not find it. Its probably due to my lack of ability to find it, but I really appreciate if you could inform me. I look forward to hearing from you.

**Comment by AxelRosendahlHuber** [comment]
Dear ykginoue, 

One of the main aims of the study was developing a method to detect low activities of colibactin mutagenesis. As can be seen in figure 1, for some organoid lines exposed to E.coli strains the indel load is so low we decided not to use these for determining colibactin mutagenesis. 

However, the deletion motif of colibactin mutagenesis motifs has been nicely described in the following paper: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7370881/  (Supplemental_Fig_S6). In our earlier study https://www.nature.com/articles/s41586-020-2080-8 we could detect this pattern as well (Extended Data Fig. 4). The deletion of a "T" in a T-homopolymer occurs in flanking "AT" matching homopolymers, with the total lenght of the A/T homopolymer sequence being 5 to 6 bases. The `select_context_indel` function from the file `pks_context_selection_functions.R` here could be of use: https://github.com/ProjectsVanBox/colibactin_detection/blob/main/Code/Functions/pks_context_selection_functions.R, 

Best wishes, Axel

**Comment by ykginoue** [comment]
Dear Axel,

Thank you for the detailed explanation and for sharing the references. I understand what you're saying, and I can now move forward with my analysis, thanks to your guidance.

Best wishes,
Yoshikage
